properties:
  consul:
    require_ssl: true
    ca_cert: CONSUL_CA_CERT
    agent_cert: CONSUL_AGENT_CERT
    agent_key: CONSUL_AGENT_KEY
    encrypt_keys:
      - CONSUL_ENCRYPT
    agent:
      servers:
        lan:
          - 127.0.0.1
  loggregator:
    etcd:
      machines:
        - etcd1.foo.bar
  loggregator_endpoint:
    shared_secret: secret123

  diego:
    rep:
      bbs:
        require_ssl: false

jobs:
  - properties:
      diego:
        rep:
          zone:
            zone1
