properties:
  consul:
    agent:
      servers:
        lan:
          - consul1.foo.bar
  etcd:
    machines:
      - etcd1.foo.bar
  loggregator_endpoint:
    shared_secret: secret123
  diego:
    rep:
      bbs:
        ca_cert: BBS_CA_CERT
        client_cert: BBS_CLIENT_CERT
        client_key: BBS_CLIENT_KEY
        require_ssl: true

jobs:
  - properties:
      diego:
        rep:
          zone:
            zone1
